#Requires -Version 5.1
<#
.SYNOPSIS
  Deploy the local OpenCode Go reverse proxy that DSH's web-search provider needs.

.DESCRIPTION
  @deepseek-ai/dsh-web-search-deepseek speaks the Anthropic-compatible Messages API and
  hard-codes its request headers, so it cannot send the x-opencode-session header the
  OpenCode Go gateway requires (missing it -> HTTP 400 MissingSessionID). This script is
  the machine-reproducible deployment of the one-file reverse proxy that adds that header:

    1. copy tools/opencode-go-proxy/proxy.js  ->  %USERPROFILE%\.dsh\opencode-go-proxy\
    2. write the hidden-window launcher and register it in the Startup folder
    3. make sure %USERPROFILE%\.dsh\settings.yaml carries the web-search-deepseek section
    4. (re)start the proxy and verify /healthz

  Idempotent: re-running only refreshes the files and restarts if the port is not answering.
  The proxy holds no credential - the API key is still sent by DSH from its credential store.

.PARAMETER Check
  Report what would change; touch nothing.

.PARAMETER SkipStart
  Deploy files but do not (re)start the proxy.

.PARAMETER VerifySearch
  After the health check, run one real search call through the proxy and assert that the
  response carries a web_search_tool_result block.

.EXAMPLE
  scripts/setup-opencode-search-proxy.ps1 -Check
  scripts/setup-opencode-search-proxy.ps1
  scripts/setup-opencode-search-proxy.ps1 -VerifySearch
#>
param(
  [switch]$Check,
  [switch]$SkipStart,
  [switch]$VerifySearch
)
$ErrorActionPreference = 'Stop'

$repo = Split-Path $PSScriptRoot -Parent
$sourceProxy = Join-Path $repo 'tools\opencode-go-proxy\proxy.js'
$dshHome = Join-Path $env:USERPROFILE '.dsh'
$proxyDir = Join-Path $dshHome 'opencode-go-proxy'
$proxyJs = Join-Path $proxyDir 'proxy.js'
$vbsLocal = Join-Path $proxyDir 'start-proxy.vbs'
$startupDir = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'
$vbsStartup = Join-Path $startupDir 'dsh-opencode-go-proxy.vbs'
$settingsFile = Join-Path $dshHome 'settings.yaml'

$port = 8787
$sessionId = 'dsh-desktop-opencode-go-search'
$userAgent = 'DSH-Desktop/2.0.13 (Windows; opencode-go-proxy/1.0)'
$searchModel = 'deepseek-v4.1-flash'
$healthUrl = "http://127.0.0.1:$port/healthz"

if (!(Test-Path $sourceProxy)) { throw "proxy source not found in repo: $sourceProxy" }

Write-Output "repo           : $repo"
Write-Output "proxy source   : $sourceProxy"
Write-Output "deploy target  : $proxyJs"
Write-Output "startup entry  : $vbsStartup"
Write-Output "settings file  : $settingsFile"
Write-Output "listen / model : http://127.0.0.1:$port/v1  |  $searchModel"

# --- 1. settings.yaml section --------------------------------------------------
$settingsNeedSection = $true
if (Test-Path $settingsFile) {
  $current = Get-Content $settingsFile -Raw
  if ($current -match '(?m)^web-search-deepseek\s*:') { $settingsNeedSection = $false }
} else {
  $current = ''
}
$settingsBlock = @"
web-search-deepseek:
  apiKeyEnv: OPENCODE_GO_API_KEY
  baseURL: http://127.0.0.1:$port/v1
  model: $searchModel
"@

if ($Check) {
  Write-Output '--- CHECK ONLY ---'
  Write-Output ("proxy.js identical to repo copy : " + ((Test-Path $proxyJs) -and ((Get-FileHash $proxyJs).Hash -eq (Get-FileHash $sourceProxy).Hash)))
  Write-Output ("startup entry present           : " + (Test-Path $vbsStartup))
  Write-Output ("settings needs web-search block : " + $settingsNeedSection)
  try {
    $h = (Invoke-WebRequest -Uri $healthUrl -TimeoutSec 5 -UseBasicParsing).Content
    Write-Output ("proxy health                    : $h")
  } catch {
    Write-Output 'proxy health                    : NOT RUNNING'
  }
  return
}

# --- 2. deploy the proxy file --------------------------------------------------
New-Item -ItemType Directory -Force $proxyDir | Out-Null
Copy-Item $sourceProxy $proxyJs -Force
Write-Output "deployed proxy.js"

# --- 3. launcher + autostart ---------------------------------------------------
$nodeExe = 'node'
$cmd = Get-Command node -ErrorAction SilentlyContinue
if ($cmd) { $nodeExe = $cmd.Source }
if (!(Test-Path $nodeExe) -and (Test-Path 'C:\nvm4w\nodejs\node.exe')) { $nodeExe = 'C:\nvm4w\nodejs\node.exe' }

$vbs = @"
' Auto-start the DSH OpenCode Go search proxy at logon (hidden window).
' Generated by scripts/setup-opencode-search-proxy.ps1 - do not edit by hand.
Set sh = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
proxyDir = "$proxyDir"
nodeExe = "$nodeExe"
If Not fso.FileExists(nodeExe) Then nodeExe = "node"
sh.CurrentDirectory = proxyDir
sh.Run """" & nodeExe & """ proxy.js", 0, False
"@
Set-Content -Path $vbsLocal -Value $vbs -Encoding ASCII
New-Item -ItemType Directory -Force $startupDir | Out-Null
Copy-Item $vbsLocal $vbsStartup -Force
Write-Output "wrote launcher + startup entry (node: $nodeExe)"

# --- 4. settings ---------------------------------------------------------------
if ($settingsNeedSection) {
  $separator = if ($current.Length -gt 0 -and -not $current.EndsWith("`n")) { "`r`n" } else { '' }
  Set-Content -Path $settingsFile -Value ($current + $separator + $settingsBlock) -Encoding UTF8
  Write-Output 'settings.yaml: appended web-search-deepseek section'
} else {
  Write-Output 'settings.yaml: web-search-deepseek section already present (left untouched)'
}

# --- 5. (re)start --------------------------------------------------------------
if ($SkipStart) { Write-Output 'SkipStart set - proxy not started'; return }

$healthy = $false
try {
  $null = Invoke-WebRequest -Uri $healthUrl -TimeoutSec 5 -UseBasicParsing
  $healthy = $true
  Write-Output 'proxy already answering /healthz'
} catch { }

if (-not $healthy) {
  Write-Output 'starting proxy via wscript ...'
  Start-Process wscript.exe -ArgumentList "`"$vbsLocal`"" -WindowStyle Hidden
  foreach ($i in 1..10) {
    Start-Sleep -Seconds 1
    try {
      $null = Invoke-WebRequest -Uri $healthUrl -TimeoutSec 3 -UseBasicParsing
      $healthy = $true
      break
    } catch { }
  }
}

if ($healthy) {
  $body = (Invoke-WebRequest -Uri $healthUrl -TimeoutSec 5 -UseBasicParsing).Content
  Write-Output "proxy OK: $body"
} else {
  throw "proxy did not answer /healthz on port $port - check $proxyDir\proxy.log"
}

# --- 6. optional end-to-end search check ---------------------------------------
if ($VerifySearch) {
  $credFile = Join-Path $dshHome '.credentials.yaml'
  $key = $null
  if (Test-Path $credFile) {
    foreach ($line in ((Get-Content $credFile -Raw) -split "`r?`n")) {
      if ($line -match '^\s*OPENCODE_GO_API_KEY\s*:\s*(.+?)\s*$') { $key = $Matches[1].Trim("'`"") }
    }
  }
  if (-not $key) { throw 'no OPENCODE_GO_API_KEY in the credential store - cannot verify search' }
  $payload = '{"model":"' + $searchModel + '","max_tokens":1024,"messages":[{"role":"user","content":[{"type":"text","text":"Perform a web search for the query: OpenAI latest news"}]}],"tools":[{"type":"web_search_20250305","name":"web_search","max_uses":3}]}'
  $resp = Invoke-WebRequest -Uri "http://127.0.0.1:$port/v1/messages" -Method Post -TimeoutSec 120 -UseBasicParsing -Body $payload `
    -Headers @{ 'x-api-key' = $key; 'authorization' = ('Bearer ' + $key); 'anthropic-version' = '2023-06-01'; 'content-type' = 'application/json'; 'accept' = 'application/json' }
  $json = $resp.Content | ConvertFrom-Json
  $rb = $json.content | Where-Object { $_.type -eq 'web_search_tool_result' }
  if ($rb) {
    Write-Output ('search OK: ' + @(@($rb)[0].content).Count + ' sources')
  } else {
    throw 'search call returned no web_search_tool_result block'
  }
}
Write-Output 'done'
